"""Artifact and ArtifactVersion domain models.

Artifacts are first-class backend deliverables generated by Limo transformation pipelines.
Security notice: Storage locations are referenced via internal `storage_ref` keys,
preventing client-controlled path traversal.
"""

from datetime import datetime, timezone
from typing import Any, Dict, Optional
from pydantic import Field, field_validator
from .base import LimoBaseModel
from .enums import ArtifactType, ValidationStatus
from ..core.ids import generate_artifact_id, generate_version_id


class Artifact(LimoBaseModel):
    """First-class generated deliverable asset produced by Limo."""

    id: str = Field(default_factory=generate_artifact_id, description="Stable artifact ID with 'art_' prefix")
    project_id: Optional[str] = Field(default=None, description="Associated project ID")
    job_id: Optional[str] = Field(default=None, description="Generating TransformationJob ID")
    title: str = Field(min_length=1, max_length=255, description="Deliverable document or media title")
    artifact_type: ArtifactType = Field(description="Deliverable category")
    file_format: str = Field(
        min_length=2,
        max_length=16,
        description="Standard file extension including leading dot (e.g. '.docx', '.pptx', '.mp4')"
    )
    storage_ref: str = Field(
        min_length=1,
        description="Internal storage reference key (e.g. 'artifacts/art_123/report.docx'). Never a trusted absolute client path."
    )
    size_bytes: int = Field(ge=0, description="File size in bytes")
    content_hash: str = Field(
        min_length=64,
        max_length=64,
        description="Cryptographic SHA-256 hash of the generated artifact content"
    )
    description: Optional[str] = Field(default=None, description="Brief summary of deliverable contents")
    stats: Optional[str] = Field(default=None, description="Display stats (e.g. '10 Slides • 16:9 • PPTX')")
    version: int = Field(default=1, ge=1, description="Current monotonic revision number")
    validation_status: ValidationStatus = Field(
        default=ValidationStatus.PENDING,
        description="Current verification and factuality status"
    )
    created_at: datetime = Field(
        default_factory=lambda: datetime.now(timezone.utc),
        description="UTC generation timestamp"
    )
    metadata: Dict[str, Any] = Field(default_factory=dict, description="Arbitrary generator/format metadata")

    @field_validator("id")
    @classmethod
    def validate_artifact_id(cls, v: str) -> str:
        if not v.startswith("art_"):
            raise ValueError("Artifact ID must start with 'art_'")
        return v

    @field_validator("file_format")
    @classmethod
    def validate_file_format(cls, v: str) -> str:
        if not v.startswith("."):
            return f".{v}"
        return v.lower()

    @field_validator("content_hash")
    @classmethod
    def validate_sha256(cls, v: str) -> str:
        if len(v) != 64 or not all(c in "0123456789abcdefABCDEF" for c in v):
            raise ValueError("Content hash must be a valid 64-character hexadecimal SHA-256 digest")
        return v.lower()


class ArtifactVersion(LimoBaseModel):
    """Historical version snapshot of a modified or regenerated artifact."""

    id: str = Field(default_factory=generate_version_id, description="Stable version ID with 'ver_' prefix")
    artifact_id: str = Field(description="Referenced parent Artifact ID")
    version_number: int = Field(ge=1, description="Monotonic version sequence number")
    storage_ref: str = Field(
        min_length=1,
        description="Internal storage key for this specific historical revision"
    )
    size_bytes: int = Field(ge=0, description="File size in bytes for this version")
    content_hash: str = Field(
        min_length=64,
        max_length=64,
        description="Cryptographic SHA-256 hash of this version's content"
    )
    change_summary: Optional[str] = Field(default=None, description="Changelog or reason for revision")
    created_at: datetime = Field(
        default_factory=lambda: datetime.now(timezone.utc),
        description="UTC version creation timestamp"
    )

    @field_validator("id")
    @classmethod
    def validate_version_id(cls, v: str) -> str:
        if not v.startswith("ver_"):
            raise ValueError("ArtifactVersion ID must start with 'ver_'")
        return v

    @field_validator("content_hash")
    @classmethod
    def validate_sha256(cls, v: str) -> str:
        if len(v) != 64 or not all(c in "0123456789abcdefABCDEF" for c in v):
            raise ValueError("Content hash must be a valid 64-character hexadecimal SHA-256 digest")
        return v.lower()
