"""Live End-to-End Verification of Phase D7.5 (Artifact Handoff to Limo).

Executes the real handoff, storage verification, REST endpoints, and chat hydration
against actual physical files generated by GenOffice.
"""

import argparse
import io
import json
import os
from pathlib import Path
import sys

# Ensure UTF-8 output on Windows consoles
if sys.platform == "win32" and sys.stdout and hasattr(sys.stdout, "reconfigure"):
    try:
        sys.stdout.reconfigure(encoding="utf-8", errors="replace")
    except Exception:
        pass

from fastapi.testclient import TestClient

from app.main import create_app
from app.models.enums import ArtifactType, FeatureMode, OutputFormat
from app.models.generation_config import GenerationConfig
from app.services.artifact_service import artifact_service
from app.services.chat_service import chat_service
from app.services.job_service import job_service
from app.services.project_service import project_service
from app.services.transformation.handoff import job_artifact_handoff_service
from app.storage.service import storage_service


def verify_live_handoff(doc_path: str, thumb_path: str, title: str = "D7.5 Live Document") -> dict:
    doc_p = Path(doc_path).resolve()
    thumb_p = Path(thumb_path).resolve()

    if not doc_p.is_file():
        raise FileNotFoundError(f"Document file not found: {doc_p}")
    if not thumb_p.is_file():
        raise FileNotFoundError(f"Thumbnail file not found: {thumb_p}")

    doc_bytes = doc_p.read_bytes()
    thumb_bytes = thumb_p.read_bytes()

    print(f"[Limo Live Handoff] Starting ingestion of '{doc_p.name}' ({len(doc_bytes)} bytes)")
    print(f"[Limo Live Handoff] Thumbnail: '{thumb_p.name}' ({len(thumb_bytes)} bytes)")

    # 1. Create project & job in Limo SQLite
    project = project_service.create_project(
        name="D7.5 Live Verification Project",
        description="End-to-End Live Handoff verification",
    )
    job = job_service.create_job(
        project_id=project.id,
        session_id=None,
        requested_formats=[OutputFormat.DOCUMENT],
        configuration=GenerationConfig(),
    )
    print(f"✓ Project ({project.id}) and Job ({job.id}) initialized")

    # 2. Ingest via job_artifact_handoff_service
    artifact = job_artifact_handoff_service.handoff_genoffice_artifact(
        job_id=job.id,
        genoffice_job_id="live_genoffice_job_001",
        genoffice_artifact={
            "file_path": str(doc_p),
            "thumbnail_path": str(thumb_p),
            "format": ".docx",
            "title": title,
        },
    )

    assert artifact.id.startswith("art_"), f"Unexpected artifact ID: {artifact.id}"
    assert storage_service.file_exists(artifact.storage_ref), "Artifact file missing in storage"
    assert storage_service.read_file(artifact.storage_ref) == doc_bytes, "Content mismatch in storage"
    assert "thumbnail_storage_ref" in artifact.metadata, "thumbnail_storage_ref missing in metadata"
    assert storage_service.file_exists(artifact.metadata["thumbnail_storage_ref"]), "Thumbnail missing in storage"
    assert storage_service.read_file(artifact.metadata["thumbnail_storage_ref"]) == thumb_bytes, "Thumbnail content mismatch"
    print(f"✓ Physical artifact ingested into Limo sandbox: {artifact.storage_ref} (id: {artifact.id})")
    print(f"✓ Thumbnail ingested into Limo sandbox: {artifact.metadata['thumbnail_storage_ref']}")

    # 3. Test REST endpoints with TestClient
    app = create_app()
    client = TestClient(app)

    # Thumbnail endpoint
    res_thumb = client.get(f"/api/v1/artifacts/{artifact.id}/thumbnail")
    assert res_thumb.status_code == 200, f"Thumbnail failed: {res_thumb.text}"
    assert res_thumb.headers["content-type"] == "image/png"
    assert res_thumb.content == thumb_bytes
    print(f"✓ GET /api/v1/artifacts/{artifact.id}/thumbnail -> HTTP 200 OK (image/png, {len(thumb_bytes)} bytes)")

    # Download endpoint
    res_down = client.get(f"/api/v1/artifacts/{artifact.id}/download")
    assert res_down.status_code == 200, f"Download failed: {res_down.text}"
    assert res_down.content == doc_bytes
    assert "attachment" in res_down.headers.get("content-disposition", "")
    print(f"✓ GET /api/v1/artifacts/{artifact.id}/download -> HTTP 200 OK (verified attachment header)")

    # Open endpoint (calls GenOffice POST /api/v1/open or OS fallback)
    res_open = client.post(f"/api/v1/artifacts/{artifact.id}/open")
    assert res_open.status_code == 200, f"Open failed: {res_open.text}"
    open_data = res_open.json()
    assert open_data["status"] == "opened"
    opener_method = open_data.get("details", {}).get("method", "workspace")
    print(f"✓ POST /api/v1/artifacts/{artifact.id}/open -> HTTP 200 OK (method: {opener_method})")

    # 4. Create chat turn and verify message hydration
    session = chat_service.create_session(title="Live Verification Chat", mode=FeatureMode.DOCS)
    chat_service.add_assistant_message(
        session_id=session.id,
        content="Here is your requested deliverable document.",
        artifact_ids=[artifact.id],
        execution_summary="Generated executive briefing using native GenOffice background view automation.",
    )

    res_msgs = client.get(f"/api/v1/chats/{session.id}/messages")
    assert res_msgs.status_code == 200
    msgs = res_msgs.json()
    assert len(msgs) == 1
    assert len(msgs[0]["artifacts"]) == 1
    hydrated_art = msgs[0]["artifacts"][0]
    assert hydrated_art["id"] == artifact.id
    assert hydrated_art["title"] == title
    assert msgs[0]["execution_summary"] == "Generated executive briefing using native GenOffice background view automation."
    print(f"✓ Chat session ({session.id}) hydrated with artifact '{artifact.title}' and safe execution summary")

    return {
        "ok": True,
        "artifact_id": artifact.id,
        "project_id": project.id,
        "job_id": job.id,
        "session_id": session.id,
        "doc_bytes": len(doc_bytes),
        "thumb_bytes": len(thumb_bytes),
        "opener_method": opener_method,
    }


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Verify D7.5 live handoff")
    parser.add_argument("--file-path", required=True, help="Path to real native document")
    parser.add_argument("--thumb-path", required=True, help="Path to real thumbnail PNG")
    parser.add_argument("--title", default="D75_Live_Document", help="Document title")
    args = parser.parse_args()

    result = verify_live_handoff(args.file_path, args.thumb_path, args.title)
    print("\n[SUCCESS] Live D7.5 Handoff Verification Completed Successfully:")
    print(json.dumps(result, indent=2))
